version: "3.8"
services:
  frontend:
    build: ./frontend
    # 起動しっぱなしにします。
    tty: true
    # 起動させ続ける Hack です。
    command: bash -c "bash /usr/local/bin/docker-entrypoint.sh && /bin/bash"
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      # この frontend を、 nginx から見れるようにします。
      - flask_hello

  nginx:
    build: ./nginx
    # 起動しっぱなしにします。
    tty: true
    expose:
      - 9090
    ports:
      - "9090:9090"
    depends_on:
      # frontend のあとに nginx をビルドします。
      - frontend
    networks:
      # この nginx から frontend が見えるようにします。
      - flask_hello


networks:
  flask_hello:
    driver: bridge